stages:
  get_data:
    cmd: python x1_get_data.py
    deps:
    - x1_get_data.py
    outs:
    - test.csv
    - train.csv
  process:
    cmd: python x2_process_data.py
    deps:
    - x2_process_data.py
    - test.csv
    - train.csv
    outs:
    - data_processed.csv
  train:
    cmd: python x3_train.py
    deps:
    - data_processed.csv
    outs:
    - ROC.png
    metrics:
    - metrics.json:
        cache: false
