name: classification
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          pip install -r requirements.txt
          dvc repro
          
          git fetch --prune
          
          dvc metrics diff --show-md main > report.md
          
          #Add figure to the report
          echo "## Validate ROC Graph"
          cml-publish ROC.png --md >> report.md
          cml-send-comment report.md
